[settings]
language = "fr_FR"
languages = ["fr_FR", "en_US"]
theme = "minerva-default"
pagefind = true

[settings.metadata.fr_FR]
name = "Minerva Exemple"
description = "Un blog de démonstration construit avec le moteur Minerva"
author = "Michaël PAULON"
date = "2024"


[settings.metadata.en_US]
name = "Minerva Example"
description = "An example blog built with the Minerva engine"
